nasa/progpy

src/progpy/data_models/lstm_model.py

Fix issue where callback to save model causes lstm training to crash in newest version of tensorflow. change from prog_models hotfix v1.5.2

Fix issue with saving model

---

src/progpy/predictors/monte_carlo.py
tests/test_predictors.py

Updated MC sample size for UWSamples state to default to just use the UWSamples directly. This is a nice quality of life and efficiency improvement. MC uses UWSamples to represent state, this way it doesn't resample from samples unnecessarily. 
Also added corresponding tests. Finally moved documentation of keyword arguments to the predict method, where it's actually used.

Improve default MC sample size

---

examples/basic_example.py
examples/horizon.py
examples/predict_specific_event.py
examples/sensitivity.py
examples/state_limits.py
src/progpy/predictors/monte_carlo.py
src/progpy/predictors/unscented_transform.py
tests/test_predictors.py

These changes make future loading optional for predictors that do not have an input (e.g., ThrownObject). This brings the behavior of predictors inline with simulation

Make future loading optional in prediction

---

src/progpy/state_estimators/particle_filter.py
tests/test_state_estimators.py

arrays and keys did not match, values were being updated incorrectly.

fixing bug: array and keys did not match in particle_filter

---

.github/workflows/python-package.yml
examples/horizon.py
src/progpy/predictors/monte_carlo.py
tests/__main__.py
tests/test_horizon.py

Ports over a few bugfix to the Monte Carlo. Fixes issue where horizon is not applied correctly. 
Also changed the example to use MultivariateNormal Distribution and added associated tests.
Thank you @kjjarvis for your work on this.

Port over changes from prog_algs hotfix v1.5.1

---

src/progpy/state_estimators/particle_filter.py

Very Minor PR
Move line where we reserve the memory for the output into the non-vectorized conditional. This memory is not used in vectorized case. In that case we allocate the memory when calling output instead. This makes that case very slightly faster.
Identified this opportunity when debugging with @mstraut

Move Memory Allocation in PF

---

examples/01_Simulation.ipynb

Add parameters example to 01_Simulation

Params Example

---

.github/workflows/python-package.yml
src/progpy/__init__.py
src/progpy/mixture_of_experts.py
src/progpy/models/test_models/other_models.py
src/progpy/utils/parameters.py
tests/__main__.py
tests/test_moe.py

First draft mixture of experts model.
This model combines multiple models. Each composite model is propogated in tandem but only the "best" one is used in output/event_state/etc.

Mixture of Experts Model

---

examples/06_Combining_Models.ipynb
src/progpy/mixture_of_experts.py

Created simple mixture of experts example demonstrating that feature

Mixture of Experts Example

---

src/progpy/mixture_of_experts.py
src/progpy/models/test_models/other_models.py
tests/test_moe.py

Previously MoE only worked with homogenous models. Now if a output, etc. is missing it will keep trying the next best model until all are completed.

Updated moe to work with different models

---

src/progpy/models/test_models/linear_models.py
src/progpy/utils/parameters.py
tests/test_base_models.py

Fixes a bug where when noise is transferred from one model to another (i.e., the noise from one model is used to set the other), the missing keys in *_noise are not set, because the object is already a DictLikeMatrix wrapper. 
This becomes an issue with models with dynamic states and events. The first of these models is being tested in the SWS project

Fix noise transfer

---

src/progpy/composite_model.py
tests/test_composite.py

Add returns of composite model function members to composite model output.

Composite Model - Add function return in output

---

examples/06_Combining_Models.ipynb
src/progpy/composite_model.py
tests/test_base_models.py
tests/test_composite.py

Closes #143
Updated composite model so that setting parameters in the composite model will update the composed models.  For example, setting "abc.def" will update parameter "def" of composed model "abc".
Also added to jupyter notebook and added test.
This feature was requested by the SWS project for a model of their SWS Safety Service

Composite Model Parameter

---

examples/01_Simulation.ipynb
examples/02_param_est.ipynb
examples/04_New Models.ipynb
examples/06_Combining_Models.ipynb
examples/07_State_Estimation.ipynb
src/progpy/prognostics_model.py
tests/test_base_models.py

Add support to set parameters directly using square brackets in the model so that
m.parameters['abc'] = 1
becomes
m['abc'] = 1
Also updated the examples to take advantage of this feature.
.parameters syntax will still work as expected (and be slightly faster), but this provides a cleaner syntax for parameters.

Direct Parameters

---

src/progpy/predictors/monte_carlo.py
src/progpy/predictors/unscented_transform.py
src/progpy/prognostics_model.py
tests/test_predictors.py

A few changes to cleanup handling of events, including:
* Allowing a single event to be passed in as a string
* Input validation
* Added tests

Clean handling of events

---

src/progpy/data_models/lstm_model.py

Workers argument has been removed from keras fit function. Also, the newest version of keras requires specifying metrics for each output (instead of a single metric to be applied to all). Updated LSTM to support this. Closes #158

Fixed issues with Tensorflow version

---

src/progpy/utils/calc_error.py

Simple error to calc error MSE where it now gives a "penalty" for the model going unstable before completing sim. The result is that parameter estimation first finds parameters that will be able to complete prediction, then it will refine them.

Calc Error Extension

---

src/progpy/data_models/lstm_model.py
src/progpy/utils/calc_error.py
tests/test_calc_error.py

Fix case where none of the profile is simulated (i.e., the model is immediately unstable)- did throw error beforehand (divide by 0).
also fixed issue with tensorflow error where outputs are duplicated

Fix 0 case

---

sphinx-config/api_ref/progpy/IncludedModels.rst
src/progpy/models/__init__.py
src/progpy/models/battery_simplified.py
tests/test_battery.py

Added model that was built in the tutorial to the models subpackage. Added to test and documentation.
Also tested by updating PHM tutorial to use this model. Confirmed behavior is the same.

Add simplified battery model from tutorial

---

tests/test_estimate_params.py

Update `tests_tolerance` to remove explicitly setting `tol` to an empty array since it no longer defaults to `False` in newer numpy version.
-----
We get the following error when we run tests_tolerance without the data-driven dependencies installed:
```
======================================================================
ERROR: test_tolerance (tests.test_estimate_params.TestEstimateParams)
Test which specifically targets adding tolerance as a keyword argument.
----------------------------------------------------------------------
Traceback (most recent call last):
 File "/Users/mly1/Documents/temp/progpy/tests/test_estimate_params.py", line 964, in test_tolerance
   m.estimate_params(times = results.times, inputs = results.inputs, outputs = results.outputs, keys = keys, tol = []) …
```

Fix tests_tolerance

---

.github/workflows/coverage.yml
.github/workflows/python-package.yml
.github/workflows/update-cache.yml

Address https://github.com/nasa/progpy/issues/185 on failing pipeline. 
- Failed pipeline run shows `Error: Missing download info for actions/cache@v2`.
- Failed pipeline run then shows the following error:
```
Version 3.7 was not found in the local cache
Error: The version '3.7' with architecture 'x64' was not found for Ubuntu 24.04.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
Resolved through the following actions:
- Upgrade cache `v2` to `v4` since the former was [deprecated](https://github.com/actions/cache?tab=readme-ov-file).
- Upgraded python `3.7` to `3.9` since version `3.7` is no longer supported and is a [known issue](https://github.com/actions/setup-python/issues/962).

Upgrade workflow cache and python version

---

examples/01_Simulation.ipynb
src/progpy/prognostics_model.py
tests/test_base_models.py

Address https://github.com/nasa/progpy/issues/186 by allowing the `thresholds_met_eqn` to be passed into `event_strategy` when using `simulate_to_threshold`.  The `thresholds_met_eqn` will be removed after the next version of ProgPy.

Allow thresholds_met_eqn argument to be passed into event_strategy in simulations

---

examples/01_Simulation.ipynb
src/progpy/prognostics_model.py
tests/test_base_models.py

Address https://github.com/nasa/progpy/issues/187 where the integration method was not being set properly. 
Issue was that the integration method was set after storing the object (`self.next_state`) values in local variables for optimization. Solved by setting the integration method before saving local variables.
Add integration method example to simulation notebook and fix related miscellaneous issues.

Fix setting integration method

---

examples/02_Parameter Estimation.ipynb

- Add table of contents
- Fix formatting for consistency

Update parameter estimation notebook

---

pyproject.toml
sphinx-config/troubleshooting.rst

Updating the supported python versions to drop 3.7 and 3.8 which are no longer actively supported by python (see https://devguide.python.org/versions/). ProgPy development policy is to not support versions once they reach python end-of-life.
This release also adds support for python 3.13 for all but data-driven features. A note is added to the troubleshooting guide for users using python3.13 with datadriven features.

Updating supported python versions

---

examples/06_Combining Models.ipynb

- Add table of contents
- Add labels to graphs
- Fix formatting for consistency

Update combining models notebook

---

examples/04_New Models.ipynb
sphinx-config/troubleshooting.rst

- Add table of contents
- Fix formatting for consistency
Same as #208

Update physics-based prognostic models notebook

---

examples/10_Prognostics Server.ipynb

- Add table of contents
- Fix formatting

Update prog_server notebook

---

src/progpy/metrics/samples.py
src/progpy/sim_result.py
src/progpy/uncertain_data/uncertain_data.py
src/progpy/utils/containers.py

Updates and refactors deprecated warnings in the codebase.
- Removes the percentage_in_bounds function from metrics/samples.py as it's deprecated.
- Comments out code related to deprecation warnings in SimResult.py to avoid redundant messages and ensure a cleaner transition.
- Modifies deprecation warnings in DictLikeMatrixWrapper to be more accurate about future behavior.
- Updates a deprecation warning message in SimResult.py to be more concise and user-friendly.
The goal is to streamline the deprecation process and provide clearer guidance to users.

Refactors deprecated warnings
